import java.util.Random;
import java.util.Scanner;

public class Task01 {
    public static void main(String[] args) {
        // Create an array with 10 randomly chosen integers
        int[] array = new int[10];
        Random rand = new Random();
        for (int i = 0; i < array.length; i++) {
            array[i] = rand.nextInt(100); // Random integers between 0 and 99
        }

        // Prompt the user to enter the index of the array
        Scanner scanner = new Scanner(System.in);
        System.out.print("Enter an index of the array: ");
        int index = scanner.nextInt();

        // Display the corresponding element value or handle out of bounds exception
        try {
            System.out.println("Element at index " + index + " is " + array[index]);
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("Out of Bounds");
        }

        scanner.close();
    }
}
-----------------------------------------------------
import java.util.Scanner;

public class Task02 {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        
        try {
            System.out.print("Enter the first integer: ");
            int num1 = scanner.nextInt();
            
            System.out.print("Enter the second integer: ");
            int num2 = scanner.nextInt();
            
            // Perform division and display the result
            int result = num1 / num2;
            System.out.println("Result: " + result);
            
        } catch (ArithmeticException e) {
            System.out.println("Cannot divide by zero.");
        } catch (Exception e) {
            System.out.println("Invalid input, please enter integer numbers.");
        }

        scanner.close();
    }
}
----------------------------------------------------------------------------------
public class Example1 {
    public static void main(String args[]) {
        int num1, num2;
        try {
            num1 = 0;
            num2 = 62 / num1;
            System.out.println(num2);
            System.out.println("Hey I'm at the end of try block");
        } catch (ArithmeticException e) {
            System.out.println("You should not divide a number by zero");
        } catch (Exception e) {
            System.out.println("Exception occurred");
        }
        System.out.println("I'm out of try-catch block in Java.");
    }
}

-----------------------------------------------------

public class Use {
    public static void main(String[] args) {
        int i = 50;
        int j = 0;
        int data;
        try {
            data = i / j;
        } catch (Exception e) {
            System.out.println(i / (j + 2));
        }
    }
}

-----------------------------------------------------

public class FinallyBlock {
    public static void main(String args[]) {
        try {
            int num = 121 / 0;
            System.out.println(num);
        } catch (ArithmeticException e) {
            System.out.println("Number should not be divided by zero");
        } finally {
            System.out.println("This is finally block");
        }
        System.out.println("Out of try-catch-finally");
    }
}

-----------------------------------------------------

public class throwExample {
    static void checkEligibilty(int age, int weight) {
        if (age < 12 && weight < 40) {
            throw new ArithmeticException("Not Eligible for registration");
        } else {
            System.out.println("Entry is Valid!!");
        }
    }

    public static void main(String args[]) {
        System.out.println("Welcome to the Registration process!!");
        checkEligibilty(10, 39);
    }
}

-----------------------------------------------------

import java.io.IOException;

public class ThrowsExample {
    void myMethod(int num) throws IOException, ClassNotFoundException {
        if (num == 1)
            throw new IOException("IOException Occurred");
        else
            throw new ClassNotFoundException("ClassNotFoundException");
    }

    public static void main(String args[]) {
        try {
            ThrowsExample obj = new ThrowsExample();
            obj.myMethod(1);
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }
}

-----------------------------------------------------

public class ArithmeticE {
    public static void main(String args[]) {
        try {
            int a = 30, b = 0;
            int c = a / b;
            System.out.println("Result = " + c);
        } catch (ArithmeticException e) {
            System.out.println("Can't divide a number by 0");
        }
    }
}

-----------------------------------------------------

public class NullpointerE {
    public static void main(String args[]) {
        try {
            String a = null;
            System.out.println(a.charAt(0));
        } catch (NullPointerException e) {
            System.out.println("NullPointerException..");
        }
    }
}

-----------------------------------------------------

public class StringIndexOutOfBound_Demo {
    public static void main(String args[]) {
        try {
            String a = "This is like chipping "; 
            char c = a.charAt(24);
            System.out.println(c);
        } catch (StringIndexOutOfBoundsException e) {
            System.out.println("StringIndexOutOfBoundsException");
        }
    }
}

-----------------------------------------------------

public class ArrayIndexOutOfBound_Demo {
    public static void main(String args[]) {
        try {
            int a[] = new int[5];
            a[6] = 9;
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("Array Index is Out Of Bounds");
        }
    }
}
------------------------------------------------------------
